name: Run Python script

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust Python version as needed

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have a requirements file

    - name: Run Python script
      run: python Projectlist.py  # Adjust the path to your Python script
